name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run lint checks
      - uses: actions/setup-node@v3
        with:
          version: 18.x
      - run: npm ci
      - run: npm run lint
