name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install python dependencies
        run: |
          python -m pip install -U pip mypy
          pip install -r flask/requirements.txt
      - name: test
        run: python3 -m unittest discover -s flask/ -p *_test.py
